#!/usr/bin/env python3
"""Regenerate board renders and the auto-generated README sections.

For every tracked KiCad board under run-*/ this renders:
  * 3D top / bottom PNGs           (kicad-cli pcb render)
  * 2D front / back layer SVGs     (kicad-cli pcb export svg)
  * a schematic PDF, if a matching .kicad_sch exists (kicad-cli sch export pdf)

into docs/renders/<run>/<board path>/, then rewrites the text between the
AUTO-GEN markers in README.md and each run-N/README.md. Everything outside the
markers is left untouched. Run READMEs that don't exist yet are created.

Usage:
  python3 .github/scripts/gen_docs.py [--version vX.Y.Z] [--skip-render]
"""

import argparse
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RENDER_DIR = Path("docs") / "renders"

START = "<!-- AUTO-GEN:START -->"
END = "<!-- AUTO-GEN:END -->"
NOTICE = ("<!-- Generated by .github/scripts/gen_docs.py on release. "
          "Edits between the AUTO-GEN markers will be overwritten. -->")

RENDER_SIZE = (1600, 1200)
FRONT_LAYERS = "F.Cu,F.Silkscreen,Edge.Cuts"
BACK_LAYERS = "B.Cu,B.Silkscreen,Edge.Cuts"

failures = []


def log(msg):
    print(msg, flush=True)


def warn(msg):
    failures.append(msg)
    # Shows up as an annotation on the GitHub Actions run.
    print(f"::warning::{msg}", flush=True)


def tracked_boards():
    """Tracked .kicad_pcb files under run-*/, sorted, as repo-relative Paths."""
    out = subprocess.run(
        ["git", "ls-files", "-z", "--", "run-*/*.kicad_pcb", "run-*/**/*.kicad_pcb"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    return sorted({Path(p) for p in out.split("\0") if p})


def run_kicad(args, output):
    output.parent.mkdir(parents=True, exist_ok=True)
    log("  kicad-cli " + " ".join(args))
    res = subprocess.run(["kicad-cli", *args], cwd=ROOT, capture_output=True, text=True)
    if res.returncode != 0 or not (ROOT / output).exists():
        warn(f"kicad-cli failed for {output}: {(res.stderr or res.stdout).strip()[-500:]}")
        return False
    return True


class Board:
    def __init__(self, pcb):
        self.pcb = pcb                                  # run-1/1x1-cob/1x1-mezzanine.kicad_pcb
        self.run = pcb.parts[0]                         # run-1
        self.rel = pcb.relative_to(self.run).with_suffix("")  # 1x1-cob/1x1-mezzanine
        self.out = RENDER_DIR / self.run / self.rel
        sch = pcb.with_suffix(".kicad_sch")
        self.sch = sch if (ROOT / sch).exists() else None

    @property
    def title(self):
        return " / ".join(self.rel.parts)

    @property
    def anchor(self):
        # GitHub heading slug: lowercase, drop punctuation, spaces -> hyphens.
        slug = re.sub(r"[^\w\- ]", "", self.title.lower())
        return slug.replace(" ", "-")

    def outputs(self):
        return {
            "top": self.out / "top.png",
            "bottom": self.out / "bottom.png",
            "front": self.out / "front.svg",
            "back": self.out / "back.svg",
            "schematic": self.out / "schematic.pdf",
        }

    def render(self):
        log(f"Rendering {self.pcb}")
        o = self.outputs()
        w, h = (str(v) for v in RENDER_SIZE)
        for side in ("top", "bottom"):
            run_kicad(["pcb", "render", "--side", side, "--width", w, "--height", h,
                       "--quality", "high", "--background", "opaque",
                       "-o", str(o[side]), str(self.pcb)], o[side])
        for side, layers, extra in (("front", FRONT_LAYERS, []),
                                    ("back", BACK_LAYERS, ["--mirror"])):
            run_kicad(["pcb", "export", "svg", "--layers", layers, "--mode-single",
                       "--page-size-mode", "2", "--exclude-drawing-sheet", *extra,
                       "-o", str(o[side]), str(self.pcb)], o[side])
        if self.sch:
            run_kicad(["sch", "export", "pdf", "-o", str(o["schematic"]), str(self.sch)],
                      o["schematic"])


def link(path, from_dir):
    """Relative POSIX link from a README's directory to a repo path."""
    return Path(os.path.relpath(ROOT / path, ROOT / from_dir)).as_posix()


def img(path, from_dir, width, alt):
    if not (ROOT / path).exists():
        return "*not available*"
    return f'<img src="{link(path, from_dir)}" width="{width}" alt="{alt}">'


def stamp(version, date):
    return f"*Generated for release **{version}** on {date}.*"


def run_block(run, boards, version, date):
    here = Path(run)
    lines = [NOTICE, "", "## Board Renders", "", stamp(version, date), ""]
    for b in boards:
        o = b.outputs()
        lines += [
            f"### {b.title}", "",
            "| 3D top | 3D bottom |", "| :---: | :---: |",
            f"| {img(o['top'], here, 400, 'top render')} "
            f"| {img(o['bottom'], here, 400, 'bottom render')} |", "",
            "| Front layers | Back layers (mirrored) |", "| :---: | :---: |",
            f"| {img(o['front'], here, 400, 'front layers')} "
            f"| {img(o['back'], here, 400, 'back layers')} |", "",
        ]
        files = [f"[PCB]({link(b.pcb, here)})"]
        if b.sch:
            files.append(f"[Schematic source]({link(b.sch, here)})")
        if (ROOT / o["schematic"]).exists():
            files.append(f"[Schematic PDF]({link(o['schematic'], here)})")
        lines += [" · ".join(files), ""]
    return "\n".join(lines).rstrip()


def root_block(runs, version, date):
    here = Path(".")
    lines = [NOTICE, "", stamp(version, date), "",
             "| Run | Board | Preview |", "| --- | --- | :---: |"]
    for run, boards in runs.items():
        readme = Path(run) / "README.md"
        for b in boards:
            lines.append(
                f"| [{run_title(run)}]({link(readme, here)}) "
                f"| [{b.title}]({link(readme, here)}#{b.anchor}) "
                f"| {img(b.outputs()['top'], here, 160, b.title)} |")
    return "\n".join(lines)


def run_title(run):
    return run.replace("-", " ").title()          # run-2 -> Run 2


def write_block(readme, block, new_header=None):
    path = ROOT / readme
    managed = f"{START}\n{block}\n{END}"
    if path.exists():
        text = path.read_text(encoding="utf-8")
    elif new_header:
        text = new_header
    else:
        warn(f"{readme} not found")
        return
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if pattern.search(text):
        text = pattern.sub(lambda _: managed, text, count=1)
    else:
        text = text.rstrip() + "\n\n---\n\n" + managed
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")
    log(f"Updated {readme}")


def detect_version():
    if os.environ.get("GITHUB_REF_TYPE") == "tag":
        return os.environ["GITHUB_REF_NAME"]
    res = subprocess.run(["git", "describe", "--tags", "--abbrev=0"],
                         cwd=ROOT, capture_output=True, text=True)
    return res.stdout.strip() if res.returncode == 0 else "unreleased"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--version", help="release name shown in the docs (default: from tag)")
    ap.add_argument("--skip-render", action="store_true",
                    help="only rewrite READMEs from existing renders")
    args = ap.parse_args()

    version = args.version or detect_version()
    date = datetime.datetime.now(datetime.timezone.utc).date().isoformat()

    runs = {}
    for pcb in tracked_boards():
        b = Board(pcb)
        runs.setdefault(b.run, []).append(b)
    if not runs:
        sys.exit("No boards found under run-*/")

    if not args.skip_render:
        for boards in runs.values():
            for b in boards:
                b.render()

    for run, boards in runs.items():
        header = (f"# {run_title(run)}\n\nThis directory holds the design files for "
                  f"**{run_title(run)}** of the [wafer.space](https://wafer.space) "
                  "chip-on-board (COB) breakouts.\n")
        write_block(Path(run) / "README.md", run_block(run, boards, version, date), header)
    write_block(Path("README.md"), root_block(runs, version, date))

    if failures:
        log(f"\n{len(failures)} step(s) failed:")
        for f in failures:
            log(f"  - {f}")
        # Docs are still written for the boards that worked; fail only if nothing rendered.
        if not any((ROOT / RENDER_DIR).rglob("*.png")):
            sys.exit(1)


if __name__ == "__main__":
    main()
